name: Docker image builder

on:
  push:
    branch: [master]

jobs:
  build:
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          echo "${{secrets.DOCKERPWD}}" | docker login -u "peltolma" --password-stdin
          docker image build -t peltolma/cse-image .
          docker push peltolma/cse-image