name: Docker image builder

on:
  workflow_dispatch:
  push:
    branch: [master]

jobs:
  build:
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t peltolma/cse-image:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: peltolma
          password: ${{ secrets.DOCKERPWD }}

      - name: Push Docker image to Docker Hub
        run: docker push peltolma/cse-image:latest